#!/usr/bin/env bash

set -euo pipefail

OPT="${1:-vapor-bluehat}"

STAGE="a"
MAJOR="1"
MINOR="1"
PATCH="$(date '+%Y%m%d%H%M')"

VERSION="$STAGE$MAJOR.$MINOR.$PATCH"

NAME="$OPT-$VERSION"
ISO_DIR="$HOME/bluebuild/isos"
ISO_PATH="$ISO_DIR/$NAME.iso"

mkdir -p "$ISO_DIR"
rm -f "$ISO_PATH"

_OLD_DIR="$PWD"

cd $ISO_DIR

sudo bluebuild generate-iso --iso-name "$NAME.iso" image ghcr.io/fyllus/vapor

cd $_OLD_DIR
