ARG BASE_IMAGE="ghcr.io/ublue-os/base-main@sha256:f87f5d4e50598688f0cb0e848c7d5a2d60179588c868fc874dae6745d2b6dbf2"
FROM "${BASE_IMAGE}" AS vapor

# This stage is responsible for holding onto
# your config without copying it directly into
# the final image
FROM scratch AS stage-files
COPY ./files /files

# Copy modules
# The default modules are inside blue-build/modules
# Custom modules overwrite defaults
FROM scratch AS stage-modules
COPY ./modules /modules

# Bins to install
# These are basic tools that are added to all images.
# Generally used for the build process. We use a multi
# stage process so that adding the bins into the image
# can be added to the ostree commits.
FROM scratch AS stage-bins
COPY --from=ghcr.io/sigstore/cosign/cosign:v3.0.5 \
  /ko-app/cosign /bins/cosign
COPY --from=ghcr.io/blue-build/cli:latest-installer \
  /out/bluebuild /bins/bluebuild
# Keys for pre-verified images
# Used to copy the keys into the final image
# and perform an ostree commit.
#
# Currently only holds the current image's
# public key.
FROM scratch AS stage-keys
COPY cosign.pub /keys/vapor.pub


# Main image
FROM vapor
ARG TARGETARCH
ARG RECIPE=recipes/recipe.yml
ARG IMAGE_REGISTRY=localhost
ARG BB_BUILD_FEATURES=""
ARG CONFIG_DIRECTORY="/tmp/files"
ARG MODULE_DIRECTORY="/tmp/modules"
ARG IMAGE_NAME="vapor"
ARG BASE_IMAGE="ghcr.io/ublue-os/base-main"
ARG FORCE_COLOR=1
ARG CLICOLOR_FORCE=1
ARG RUST_LOG_STYLE=always
# Key RUN
RUN --mount=type=bind,from=stage-keys,src=/keys,dst=/tmp/keys \
  mkdir -p /etc/pki/containers/ \
  && cp /tmp/keys/* /etc/pki/containers/
# Bin RUN
RUN --mount=type=bind,from=stage-bins,src=/bins,dst=/tmp/bins \
  mkdir -p /usr/bin/ \
  && cp /tmp/bins/* /usr/bin/
RUN --mount=type=bind,from=ghcr.io/blue-build/nushell-image:default,src=/nu,dst=/tmp/nu \
  mkdir -p /usr/libexec/bluebuild/nu \
  && cp -r /tmp/nu/* /usr/libexec/bluebuild/nu/
RUN \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/scripts/,Z \
  /scripts/pre_build.sh

# Module RUNs
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/files:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-vapor-latest-stage-vapor \
/tmp/scripts/run_module.sh 'files' '{"type":"files","files":[{"source":"system","destination":"/"}]}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/dnf:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-vapor-latest-stage-vapor \
/tmp/scripts/run_module.sh 'dnf' '{"type":"dnf","install":{"packages":["xorg-x11-server-Xwayland","gnome-initial-setup","gdm","steam","gamescope","bluez","NetworkManager-wifi","NetworkManager-libnm","google-noto-sans-fonts","dejavu-sans-fonts","exfatprogs","ntfs-3g","mesa-dri-drivers","mesa-vulkan-drivers","vulkan-loader","virglrenderer"]}}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/systemd:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-vapor-latest-stage-vapor \
/tmp/scripts/run_module.sh 'systemd' '{"type":"systemd","system":{"enabled":["gdm.service","bluetooth.service","NetworkManager.service"]}}'
RUN \
--mount=type=bind,from=stage-files,src=/files,dst=/tmp/files,rw \
--mount=type=bind,from=ghcr.io/blue-build/modules/script:latest,src=/modules,dst=/tmp/modules,rw \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/tmp/scripts/,Z \
--mount=type=cache,sharing=locked,dst=/var/cache/rpm-ostree,id=rpm-ostree-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/libdnf5,id=dnf-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/zypp,id=zypper-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apk,id=apk-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/apt,id=apt-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/var/cache/pacman,id=pacman-cache-vapor-latest-stage-vapor \
--mount=type=cache,sharing=locked,dst=/usr/lib/sysimage/cache/pacman,id=pacman-sysimage-cache-vapor-latest-stage-vapor \
/tmp/scripts/run_module.sh 'script' '{"type":"script","scripts":["service-disable.sh"]}'

RUN \
--mount=type=bind,src=.bluebuild-scripts_6fc443c6,dst=/scripts/,Z \
  /scripts/post_build.sh

# Labels are added last since they cause cache misses with buildah
LABEL io.artifacthub.package.readme-url="https://raw.githubusercontent.com/blue-build/cli/main/README.md"
LABEL org.blue-build.build-id="6bde9be9-6cf9-4b6f-88f7-ae64d3cacdf9"
LABEL org.opencontainers.image.base.digest="sha256:f87f5d4e50598688f0cb0e848c7d5a2d60179588c868fc874dae6745d2b6dbf2"
LABEL org.opencontainers.image.base.name="ghcr.io/ublue-os/base-main:latest"
LABEL org.opencontainers.image.created="2026-07-21T06:21:02.011238164+00:00"
LABEL org.opencontainers.image.description="Blue like Steam, but light as vapor."
LABEL org.opencontainers.image.source=""
LABEL org.opencontainers.image.title="vapor"